### ISSUE TITLE
Cinnabar Clusters

### ISSUE THREAD

**Issue by shank3001** [Belgabor/Magicality#21]
It appears that we cannot progress through Thaumic Tinkerer because there is no way to get cinnabar clusters. Not sure if this was intended?

**Comment by Belgabor** [comment]
Not sure what you are referring to, mining cinnabar ore with a pickaxe of the core works fine.

**Comment by shank3001** [comment]
No cinnabar ore was spawned. Looked in twilight, spirit world, and overworld.

**Comment by bengalgod** [comment]
You want the orechid. It's functional flora from botania.

**Comment by Belgabor** [comment]
Exactly
