### ISSUE TITLE
[question] collector

### ISSUE THREAD

**Issue by someguyfromdownthestreet** [Belgabor/Magicality#22]
i have all thaumcraft research unlocked (tested by rightclicking with research from 9 knowledge fragments and i have everything with EMC unlocked(gained by burning an alchemical tome)

**Comment by itanshi** [comment]
I'll rephrase. We have all research from the thaumonomicon. We made a think tank and are unable to get more research notes from knowledge fragments. The tool tip on 'collector mk1' mentions 'whispers' which makes us think the Eldritch tab. So, how may we obtain this item?

**Comment by haighyorkie** [comment]
It's not Thaumcraft related ;)

**Comment by Belgabor** [comment]
We might want to change the tooltip to not give a wrong impression. It's just meant to hint that the item is available and not fully deactivated.

**Comment by someguyfromdownthestreet** [comment]
we also have all quests done

**Comment by Belgabor** [comment]
I don't want to spoil it, but you might want to progress more on a certain mod you apparently have neglected =)

**Comment by someguyfromdownthestreet** [comment]
ok thanks that is actually helpful :D now i wont be endlessly hunting through creative tabs trying to think of something
